# Generated by Django 2.1 on 2018-08-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0003_auto_20180822_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='added_date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
