# Generated by Django 2.1 on 2018-08-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0004_auto_20180822_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='category',
            new_name='topic',
        ),
    ]
